version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:16.3.0
    working_directory: ~/BHelpful
    steps:
      - checkout:
          path: ~/BHelpful
      - run:
          name: Install dependencies
          command: |
            yarn install --ignore-engines
      - run:
          name: Run tests
          command: |
            yarn test
workflows:
  CI_Tests:
    jobs:
      - run_tests