name: New Story
description: Create a new story
title: "[Story]: "
labels: [story]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for creating a new story to improve our product!
  - type: dropdown
    id: project
    attributes:
      label: Project/Library/Tool
      description: The Project/Library/Tool in the monorepo that this issue is relevant for
      options:
        - MealPlanr
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - MAJOR
        - MINOR
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: The user story for the feature.
      placeholder: As a user, I would like to ... so I can ...
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: The criteria for which the story will be accepted in a Pull Request.
      placeholder: The implementation should have ...
      value: |
        - [ ]
    validations:
      required: true
  - type: textarea
    id: comments-questions
    attributes:
      label: Comments / questions
      description: Any comments or questions relating the story (Any UX should be but here for the developers to see).
      placeholder: We should divide this into sub-tasks...
  - type: textarea
    id: dor-dod
    attributes:
      label: Definition of ready/done (DOR/DOD) [DON'T CHANGE THE CONTENT]
      description: This field is not to be changed!
      value: |
        #### Definition of ready
        - [ ] DOR
            <details>
            <summary>Description</summary>

            ```
            - Acceptance criteria written and reviewed by QA, PM and SE
            - Behavior scenarios written
            - Signed off UX
            - Estimated and appropriately scoped
            ```

            </details>

        #### Definition of done
        - [ ] DOD
            <details>
            <summary>Description</summary>

            ```
            - Test complete
                - Merged to master
                - Unit tests on all new code (80% coverage)
                - Integration tests for endpoints / web sockets
                - End-to-end or integration tests verifying acceptance criteria
            - Code complete
                - Peer reviewed (1 person/people)
                - Follows BHelpful code standards / versioning guidelines
                - No commented out code or TODOs
                - Linting / Sonarcloud exceptions have explicit explanations
            - Verified by QA
                - Functionally manually verified on a setup like the actual setup
                - QA verifies test coverage aligns with master test plan
            - Verified by UX and product owner / verified by the team
            - Documentation of tech debt
            - Persistent technical documentation updated / written
                - Ready is updated / written
            ```

            </details>
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/BHelpful/BHelpful/blob/master/DOCS/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
