name: rebase pull requests
on:
  push:
    branches:
      - master

jobs:
  auto-rebase:
    name: rebase dependabot PRs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.event == 'release'
    timeout-minutes: 5
    steps:
      - name: rebase
        uses: "bbeesley/gha-auto-dependabot-rebase@v1.1.0"
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
