name: rebase pull requests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  wait_for_changes:
    name: Wait for changes to get into the repo
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 15 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: "15s"
  auto-rebase:
    name: rebase dependabot PRs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.event == 'release'
    timeout-minutes: 5
    steps:
      - name: rebase
        uses: "bbeesley/gha-auto-dependabot-rebase@v1.1.0"
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
