name: Enable auto merge PR

on:
  pull_request:
    types: [review_requested, ready_for_review]

permissions:
  pull-requests: write
  contents: write

jobs:
  Enable_auto_merge_pr:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      # Finally, this sets the PR to allow auto-merging for patch and minor
      # updates if all checks pass
      - name: Enable auto-merge for PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
