name: "Set Issue Label for projects"
on:
  issues:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["MealPlanr"]'
          labels: '["MealPlanr"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      # Self hosted deploy server cleanup, should ALWAYS run independent to result
      - name: Cleanup
        if: ${{ always() }}
        run: docker ps -q | xargs -n 1 -P 8 -I {} docker stop {}
